name: Mise à jour du fichier index.html

on:
  workflow_dispatch:
  push:
    paths:
      - "nouveau-index.html"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Remplacer le fichier index.html
        run: |
          mv nouveau-index.html index.html
          git add index.html
          git commit -m "Mise à jour automatique des listes"
          git push
