name: Mise à jour du fichier index.html

on:
  workflow_dispatch:
  push:
    paths:
      - "listes-partenaires.html"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Configurer l'utilisateur Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Remplacer le fichier index.html
        run: |
          mv listes-partenaires.html listes.html
          git add listes.html
          git commit -m "Mise à jour automatique des listes"
          git push origin main --force
    env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
